/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectschoolinterface.FrontEnd.menuGui;

/**
 *
 * @author goomezcode
 */
public class cadastroMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(cadastroMenu.class.getName());

    /**
     * Creates new form cadastroMenu
     */
    public cadastroMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroStudent = new javax.swing.JButton();
        cadastroEmployee = new javax.swing.JButton();
        panelStudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cpf2 = new javax.swing.JTextField();
        nome2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        serieEscolar2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nomeMae2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        rg2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        idade2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        nomePai2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroStudent.setVisible(false);
        cadastroStudent.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        cadastroStudent.setText("Student");
        cadastroStudent.addActionListener(this::cadastroStudentActionPerformed);

        cadastroEmployee.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        cadastroEmployee.setText("Employee");
        cadastroEmployee.addActionListener(this::cadastroEmployeeActionPerformed);

        panelStudent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Student");

        cpf2.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        cpf2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpf2.addActionListener(this::cpf2ActionPerformed);

        nome2.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        nome2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nome2.addActionListener(this::nome2ActionPerformed);

        serieEscolar2.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        serieEscolar2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serieEscolar2.addActionListener(this::serieEscolar2ActionPerformed);

        jLabel18.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel18.setText("Nome Pai: ");

        jLabel19.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel19.setText("Idade");

        jLabel20.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel20.setText("Serie Escolar:");

        jLabel21.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel21.setText("Rg:");

        nomeMae2.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        nomeMae2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeMae2.addActionListener(this::nomeMae2ActionPerformed);

        jLabel22.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel22.setText("Nome Mãe: ");

        rg2.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        rg2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rg2.addActionListener(this::rg2ActionPerformed);

        jLabel23.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel23.setText("Cpf:");

        idade2.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        idade2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idade2.addActionListener(this::idade2ActionPerformed);

        jLabel24.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel24.setText("Nome:");

        nomePai2.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        nomePai2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomePai2.addActionListener(this::nomePai2ActionPerformed);

        jButton1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jButton1.setText("Submit");

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel22))
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                            .addComponent(nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116)))
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rg2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpf2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomePai2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeMae2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serieEscolar2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idade2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
            .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStudentLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idade2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(12, 12, 12)
                .addComponent(serieEscolar2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeMae2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomePai2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpf2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rg2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStudentLayout.createSequentialGroup()
                    .addGap(334, 334, 334)
                    .addComponent(jLabel17)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cadastroStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastroEmployee))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroStudentActionPerformed
        // TODO add your handling code here:
        cadastroStudent.setVisible(false);
        cadastroEmployee.setVisible(true);
        panelStudent.setVisible(true);
    }//GEN-LAST:event_cadastroStudentActionPerformed

    private void cadastroEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroEmployeeActionPerformed
        // TODO add your handling code here:
        cadastroStudent.setVisible(true);
        cadastroEmployee.setVisible(false);
        panelStudent.setVisible(false);
    }//GEN-LAST:event_cadastroEmployeeActionPerformed

    private void nomePai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePai2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePai2ActionPerformed

    private void idade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idade2ActionPerformed

    private void rg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rg2ActionPerformed

    private void nomeMae2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMae2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMae2ActionPerformed

    private void serieEscolar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieEscolar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serieEscolar2ActionPerformed

    private void nome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome2ActionPerformed

    private void cpf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new cadastroMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroEmployee;
    private javax.swing.JButton cadastroStudent;
    private javax.swing.JTextField cpf2;
    private javax.swing.JTextField idade2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JTextField nome2;
    private javax.swing.JTextField nomeMae2;
    private javax.swing.JTextField nomePai2;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JTextField rg2;
    private javax.swing.JTextField serieEscolar2;
    // End of variables declaration//GEN-END:variables
}
