/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectschoolinterface.FrontEnd.menuGui;

/**
 *
 * @author goomezcode
 */
public class cadastroMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(cadastroMenu.class.getName());

    /**
     * Creates new form cadastroMenu
     */
    public cadastroMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroStudent = new javax.swing.JButton();
        cadastroEmployee = new javax.swing.JButton();
        panelStudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cpfStudent = new javax.swing.JTextField();
        nomeStudent = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        serieEscolarStudent = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nomeMaeStudent = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        rgStudent = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        idadeStudent = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        nomePaiStudent = new javax.swing.JTextField();
        submitStudent = new javax.swing.JButton();
        panelEmployee = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cpf3 = new javax.swing.JTextField();
        nome3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        serieEscolar3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nomeMae3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rg3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        idade3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        nomePai3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroStudent.setVisible(false);
        cadastroStudent.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        cadastroStudent.setText("Student");
        cadastroStudent.addActionListener(this::cadastroStudentActionPerformed);

        cadastroEmployee.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        cadastroEmployee.setText("Employee");
        cadastroEmployee.addActionListener(this::cadastroEmployeeActionPerformed);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Student");

        cpfStudent.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        cpfStudent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpfStudent.addActionListener(this::cpfStudentActionPerformed);

        nomeStudent.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        nomeStudent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeStudent.addActionListener(this::nomeStudentActionPerformed);

        serieEscolarStudent.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        serieEscolarStudent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serieEscolarStudent.addActionListener(this::serieEscolarStudentActionPerformed);

        jLabel18.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Nome Pai: ");

        jLabel19.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Idade");

        jLabel20.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Serie Escolar:");

        jLabel21.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Rg:");

        nomeMaeStudent.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        nomeMaeStudent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeMaeStudent.addActionListener(this::nomeMaeStudentActionPerformed);

        jLabel22.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Nome Mãe: ");

        rgStudent.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        rgStudent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rgStudent.addActionListener(this::rgStudentActionPerformed);

        jLabel23.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Cpf:");

        idadeStudent.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        idadeStudent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idadeStudent.addActionListener(this::idadeStudentActionPerformed);

        jLabel24.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Nome:");

        nomePaiStudent.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        nomePaiStudent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomePaiStudent.addActionListener(this::nomePaiStudentActionPerformed);

        submitStudent.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        submitStudent.setText("Submit");

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(submitStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                                .addComponent(nomeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGroup(panelStudentLayout.createSequentialGroup()
                            .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rgStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpfStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomePaiStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomeMaeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(serieEscolarStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idadeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
            .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStudentLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idadeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serieEscolarStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeMaeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomePaiStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rgStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStudentLayout.createSequentialGroup()
                    .addGap(334, 334, 334)
                    .addComponent(jLabel17)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );

        panelEmployee.setVisible(false);

        jLabel2.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro Employee");

        cpf3.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        cpf3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpf3.addActionListener(this::cpf3ActionPerformed);

        nome3.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        nome3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nome3.addActionListener(this::nome3ActionPerformed);

        serieEscolar3.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        serieEscolar3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serieEscolar3.addActionListener(this::serieEscolar3ActionPerformed);

        jLabel26.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Nome Pai: ");

        jLabel27.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Idade");

        jLabel28.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Serie Escolar:");

        jLabel29.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Rg:");

        nomeMae3.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        nomeMae3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeMae3.addActionListener(this::nomeMae3ActionPerformed);

        jLabel30.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Nome Mãe: ");

        rg3.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        rg3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rg3.addActionListener(this::rg3ActionPerformed);

        jLabel31.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Cpf:");

        idade3.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        idade3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idade3.addActionListener(this::idade3ActionPerformed);

        jLabel32.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Nome:");

        nomePai3.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        nomePai3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomePai3.addActionListener(this::nomePai3ActionPerformed);

        jButton2.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jButton2.setText("Submit");

        javax.swing.GroupLayout panelEmployeeLayout = new javax.swing.GroupLayout(panelEmployee);
        panelEmployee.setLayout(panelEmployeeLayout);
        panelEmployeeLayout.setHorizontalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmployeeLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEmployeeLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel28)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmployeeLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel30))
                    .addGroup(panelEmployeeLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                            .addComponent(nome3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116)))
                    .addGroup(panelEmployeeLayout.createSequentialGroup()
                        .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rg3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpf3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomePai3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeMae3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serieEscolar3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idade3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
            .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEmployeeLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );
        panelEmployeeLayout.setVerticalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idade3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(12, 12, 12)
                .addComponent(serieEscolar3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeMae3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomePai3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpf3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rg3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEmployeeLayout.createSequentialGroup()
                    .addGap(334, 334, 334)
                    .addComponent(jLabel25)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cadastro Employee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(cadastroStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroEmployee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroStudentActionPerformed
        // TODO add your handling code here:
        cadastroStudent.setVisible(false);
        cadastroEmployee.setVisible(true);
        panelStudent.setVisible(true);
        panelEmployee.setVisible(false);
        jLabel3.setText("Cadastro Employee");
    }//GEN-LAST:event_cadastroStudentActionPerformed

    private void cadastroEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroEmployeeActionPerformed
        // TODO add your handling code here:
        cadastroStudent.setVisible(true);
        cadastroEmployee.setVisible(false);
        panelStudent.setVisible(false);
        panelEmployee.setVisible(true);
        jLabel3.setText("Cadastro Student");
    }//GEN-LAST:event_cadastroEmployeeActionPerformed

    private void nomePaiStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePaiStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePaiStudentActionPerformed

    private void idadeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeStudentActionPerformed

    private void rgStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgStudentActionPerformed

    private void nomeMaeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMaeStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMaeStudentActionPerformed

    private void serieEscolarStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieEscolarStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serieEscolarStudentActionPerformed

    private void nomeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeStudentActionPerformed

    private void cpfStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfStudentActionPerformed

    private void cpf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf3ActionPerformed

    private void nome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome3ActionPerformed

    private void serieEscolar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieEscolar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serieEscolar3ActionPerformed

    private void nomeMae3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMae3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMae3ActionPerformed

    private void rg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rg3ActionPerformed

    private void idade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idade3ActionPerformed

    private void nomePai3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePai3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePai3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new cadastroMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroEmployee;
    private javax.swing.JButton cadastroStudent;
    private javax.swing.JTextField cpf3;
    private javax.swing.JTextField cpfStudent;
    private javax.swing.JTextField idade3;
    private javax.swing.JTextField idadeStudent;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JTextField nome3;
    private javax.swing.JTextField nomeMae3;
    private javax.swing.JTextField nomeMaeStudent;
    private javax.swing.JTextField nomePai3;
    private javax.swing.JTextField nomePaiStudent;
    private javax.swing.JTextField nomeStudent;
    private javax.swing.JPanel panelEmployee;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JTextField rg3;
    private javax.swing.JTextField rgStudent;
    private javax.swing.JTextField serieEscolar3;
    private javax.swing.JTextField serieEscolarStudent;
    private javax.swing.JButton submitStudent;
    // End of variables declaration//GEN-END:variables
}
